### ISSUE TITLE
Getting a list of payments

### ISSUE THREAD

**Issue by maxdaniel98** [JvanHengel/BunqSDK#2]
Is it possible to get a list of payments using this SDK? 
The request is listed here (https://doc.bunq.com/api/1/call/payment/method/list) but I'm not able to get that working in this SDK.

**Comment by JvanHengel** [comment]
The LIST method is currently not supported yet, but I'll be looking into it right away!

**Comment by JvanHengel** [comment]
From now on you should be able to call the method list_($bunqObject, count) in the BunqSession.
